<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tweety">
<meta name="dcterms.date" content="2026-02-11">

<title>Intuit Quickbooks Upgrade – Tweety’s website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Tweety’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./AB_Testing.html"> 
<span class="menu-text">A/B Testing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Maximum_Likelihood_Estimation.html"> 
<span class="menu-text">MLE</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Intuit_Quickbooks_Upgrade.html" aria-current="page"> 
<span class="menu-text">Uplift Modeling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Key_Drivers_Analysis.html"> 
<span class="menu-text">Key Drivers Analysis</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#data-and-problem-setup" id="toc-data-and-problem-setup" class="nav-link" data-scroll-target="#data-and-problem-setup">Data and Problem Setup</a>
  <ul class="collapse">
  <li><a href="#data-source-and-unit-of-analysis" id="toc-data-source-and-unit-of-analysis" class="nav-link" data-scroll-target="#data-source-and-unit-of-analysis">Data source and unit of analysis</a></li>
  <li><a href="#outcome-definition" id="toc-outcome-definition" class="nav-link" data-scroll-target="#outcome-definition">Outcome definition</a></li>
  <li><a href="#predictor-variables-summary" id="toc-predictor-variables-summary" class="nav-link" data-scroll-target="#predictor-variables-summary">Predictor variables (summary)</a></li>
  <li><a href="#trainvalidation-split" id="toc-trainvalidation-split" class="nav-link" data-scroll-target="#trainvalidation-split">Train/validation split</a></li>
  <li><a href="#data-dictionary" id="toc-data-dictionary" class="nav-link" data-scroll-target="#data-dictionary">Data dictionary</a></li>
  </ul></li>
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory Analysis</a>
  <ul class="collapse">
  <li><a href="#response-rate-by-zip-bin" id="toc-response-rate-by-zip-bin" class="nav-link" data-scroll-target="#response-rate-by-zip-bin">Response rate by ZIP bin</a></li>
  <li><a href="#zip5-drill-down-within-zip_bins-1" id="toc-zip5-drill-down-within-zip_bins-1" class="nav-link" data-scroll-target="#zip5-drill-down-within-zip_bins-1">ZIP5 drill-down within zip_bins = 1</a></li>
  <li><a href="#confirming-the-anomaly-zips-00801-and-00804" id="toc-confirming-the-anomaly-zips-00801-and-00804" class="nav-link" data-scroll-target="#confirming-the-anomaly-zips-00801-and-00804">Confirming the anomaly ZIPs: 00801 and 00804</a></li>
  </ul></li>
  <li><a href="#modeling-approach" id="toc-modeling-approach" class="nav-link" data-scroll-target="#modeling-approach">Modeling Approach</a>
  <ul class="collapse">
  <li><a href="#baselines-logistic-regression-lr1lr2" id="toc-baselines-logistic-regression-lr1lr2" class="nav-link" data-scroll-target="#baselines-logistic-regression-lr1lr2">Baselines: logistic regression (LR1–LR2)</a></li>
  <li><a href="#feature-refinement-version-path-construction" id="toc-feature-refinement-version-path-construction" class="nav-link" data-scroll-target="#feature-refinement-version-path-construction">Feature refinement: version path construction</a></li>
  <li><a href="#benchmark-mail-to-all-strategy" id="toc-benchmark-mail-to-all-strategy" class="nav-link" data-scroll-target="#benchmark-mail-to-all-strategy">Benchmark: mail-to-all strategy</a></li>
  <li><a href="#neural-network-exploration" id="toc-neural-network-exploration" class="nav-link" data-scroll-target="#neural-network-exploration">Neural network exploration</a></li>
  <li><a href="#lr3-logistic-regression-with-interactions" id="toc-lr3-logistic-regression-with-interactions" class="nav-link" data-scroll-target="#lr3-logistic-regression-with-interactions">LR3: logistic regression with interactions</a></li>
  </ul></li>
  <li><a href="#recommendation-and-expected-impact" id="toc-recommendation-and-expected-impact" class="nav-link" data-scroll-target="#recommendation-and-expected-impact">Recommendation and Expected Impact</a>
  <ul class="collapse">
  <li><a href="#recommended-wave-2-targeting-rule" id="toc-recommended-wave-2-targeting-rule" class="nav-link" data-scroll-target="#recommended-wave-2-targeting-rule">Recommended wave-2 targeting rule</a></li>
  <li><a href="#expected-financial-impact" id="toc-expected-financial-impact" class="nav-link" data-scroll-target="#expected-financial-impact">Expected financial impact</a></li>
  <li><a href="#operational-notes" id="toc-operational-notes" class="nav-link" data-scroll-target="#operational-notes">Operational notes</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Intuit Quickbooks Upgrade</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tweety </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 11, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This project builds a predictive response model for <a href="https://www.intuit.com">Intuit’s QuickBooks</a> upgrade upsell campaign. The dataset (intuit75k.parquet) contains 75,000 small businesses randomly sampled from the 801,821 businesses that received the wave-1 mailing. Each business record includes customer attributes and purchase history that can be used to estimate the likelihood of upgrading.</p>
<p>The response variable res1 indicates whether a business purchased QuickBooks version 3.0 through Intuit Direct after receiving the wave-1 offer. Because the case materials have been modified (variables added, removed, and recoded), the analysis relies on the updated variable definitions provided in this report rather than Exhibit 3 in the course reader.</p>
<hr>
</section>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<p>Deliver a wave-2 targeting approach that increases incremental profit versus untargeted mailing. Specifically, we (1) estimate each business’s likelihood of responding to wave-2, (2) translate predicted responses into expected profit using campaign economics, and (3) recommend a mailing cutoff rule that sends offers only when expected return exceeds break-even.</p>
<hr>
</section>
<section id="data-and-problem-setup" class="level2">
<h2 class="anchored" data-anchor-id="data-and-problem-setup">Data and Problem Setup</h2>
<section id="data-source-and-unit-of-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-source-and-unit-of-analysis">Data source and unit of analysis</h3>
<p>Each row represents a small-business customer in Intuit Direct’s mailing file. The analysis uses the sample provided in <code>intuit75k.parquet</code>, drawn from wave-1 recipients.</p>
</section>
<section id="outcome-definition" class="level3">
<h3 class="anchored" data-anchor-id="outcome-definition">Outcome definition</h3>
<ul>
<li><strong><code>res1</code></strong> is the response indicator for the wave-1 mailing (<strong>“Yes”</strong> = purchased QuickBooks 3.0 through Intuit Direct; <strong>“No”</strong> otherwise).<br>
</li>
<li>The modeling task is a binary classification problem used for <strong>ranking customers</strong> for wave-2 targeting.</li>
</ul>
</section>
<section id="predictor-variables-summary" class="level3">
<h3 class="anchored" data-anchor-id="predictor-variables-summary">Predictor variables (summary)</h3>
<p>The predictors describe customer location, business indicators, and purchase behavior over the prior 36 months, plus product/version history. A full data dictionary is included below.</p>
</section>
<section id="trainvalidation-split" class="level3">
<h3 class="anchored" data-anchor-id="trainvalidation-split">Train/validation split</h3>
<ul>
<li><strong><code>training</code> = 1</strong> indicates the training sample (70%).<br>
</li>
<li><strong><code>training</code> = 0</strong> indicates the validation sample (30%).<br>
Model selection and thresholding decisions are based on validation performance.</li>
</ul>
</section>
<section id="data-dictionary" class="level3">
<h3 class="anchored" data-anchor-id="data-dictionary">Data dictionary</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>id</code></td>
<td>Small business customer ID</td>
</tr>
<tr class="even">
<td><code>zip5</code></td>
<td>5-digit ZIP code (00000 = unknown, 99999 = international ZIPs)</td>
</tr>
<tr class="odd">
<td><code>zip_bins</code></td>
<td>ZIP-code bins (≈20 roughly equal-sized bins from lowest to highest ZIP number)</td>
</tr>
<tr class="even">
<td><code>sex</code></td>
<td>Gender identity: Female, Male, or Unknown</td>
</tr>
<tr class="odd">
<td><code>bizflag</code></td>
<td>Business flag: address contains a business name (1 = yes, 0 = no/unknown)</td>
</tr>
<tr class="even">
<td><code>numords</code></td>
<td>Number of Intuit Direct orders in the previous 36 months</td>
</tr>
<tr class="odd">
<td><code>dollars</code></td>
<td>Total dollars ordered from Intuit Direct in the previous 36 months</td>
</tr>
<tr class="even">
<td><code>last</code></td>
<td>Months since last Intuit Direct order (within the previous 36 months)</td>
</tr>
<tr class="odd">
<td><code>sincepurch</code></td>
<td>Months since original (non-upgrade) QuickBooks purchase</td>
</tr>
<tr class="even">
<td><code>version1</code></td>
<td>1 if current QuickBooks is version 1; 0 if version 2</td>
</tr>
<tr class="odd">
<td><code>owntaxprod</code></td>
<td>1 if customer purchased tax software; 0 otherwise</td>
</tr>
<tr class="even">
<td><code>upgraded</code></td>
<td>1 if customer upgraded previously (vs.&nbsp;purchasing a base version); 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>res1</code></td>
<td>Response to wave-1 mailing (“Yes” / “No”)</td>
</tr>
<tr class="even">
<td><code>training</code></td>
<td>Split indicator (1 = training, 0 = validation)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis">Exploratory Analysis</h2>
<section id="response-rate-by-zip-bin" class="level3">
<h3 class="anchored" data-anchor-id="response-rate-by-zip-bin">Response rate by ZIP bin</h3>
<p>Wave-1 response varies materially across <code>zip_bins</code>. One segment is a clear outlier: <code>zip_bins = 1</code> has a response rate of <strong>0.2185</strong>, while all other bins fall between <strong>0.0331</strong> and <strong>0.0519</strong>. Bin sizes are comparable across segments (~3,700–3,800 customers), so the difference is not driven by uneven volume.</p>
<p><strong>Wave-1 response rate by ZIP bin (sorted by response rate)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">zip_bins</th>
<th style="text-align: right;">response_rate (<code>res1_yes</code>)</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.218525</td>
<td style="text-align: right;">3757</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.051934</td>
<td style="text-align: right;">3774</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.049281</td>
<td style="text-align: right;">3754</td>
</tr>
<tr class="even">
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.043747</td>
<td style="text-align: right;">3726</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.043258</td>
<td style="text-align: right;">3745</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.041589</td>
<td style="text-align: right;">3751</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.039498</td>
<td style="text-align: right;">3747</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.039221</td>
<td style="text-align: right;">3748</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.038215</td>
<td style="text-align: right;">3742</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.037877</td>
<td style="text-align: right;">3749</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.037323</td>
<td style="text-align: right;">3751</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.037077</td>
<td style="text-align: right;">3749</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.036820</td>
<td style="text-align: right;">3748</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.036553</td>
<td style="text-align: right;">3748</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.036465</td>
<td style="text-align: right;">3757</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.036041</td>
<td style="text-align: right;">3718</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.035181</td>
<td style="text-align: right;">3752</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.034124</td>
<td style="text-align: right;">3751</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.034109</td>
<td style="text-align: right;">3782</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.033058</td>
<td style="text-align: right;">3751</td>
</tr>
</tbody>
</table>
<p><strong>Action taken.</strong> The outlier behavior in <code>zip_bins = 1</code> is treated as a localized segment effect and is decomposed to ZIP5 to identify the driver.</p>
</section>
<section id="zip5-drill-down-within-zip_bins-1" class="level3">
<h3 class="anchored" data-anchor-id="zip5-drill-down-within-zip_bins-1">ZIP5 drill-down within zip_bins = 1</h3>
<p>Two ZIP codes within <code>zip_bins = 1</code> account for the unusually high response rates at meaningful volumes:</p>
<p><strong>ZIP5 segments within <code>zip_bins = 1</code> with response_rate &gt; 0.30 and n &gt; 50</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>zip5</th>
<th style="text-align: right;">response_rate (<code>res1_yes</code>)</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>00801</td>
<td style="text-align: right;">0.412470</td>
<td style="text-align: right;">1668</td>
</tr>
<tr class="even">
<td>00804</td>
<td style="text-align: right;">0.344086</td>
<td style="text-align: right;">186</td>
</tr>
</tbody>
</table>
<p>These ZIP codes are captured explicitly in modeling using an indicator variable (<code>isweird</code>) to prevent the effect from being diluted across broader ZIP binning.</p>
</section>
<section id="confirming-the-anomaly-zips-00801-and-00804" class="level3">
<h3 class="anchored" data-anchor-id="confirming-the-anomaly-zips-00801-and-00804">Confirming the anomaly ZIPs: 00801 and 00804</h3>
<p>To determine whether the elevated response observed in <code>zip_bins = 1</code> reflects a broader ZIP-level pattern, ZIP5 response rates were reviewed across the full dataset with minimum-volume filters (response rate &gt; 0.20 and n &gt; 40). Only <strong>00801</strong> and <strong>00804</strong> met these criteria. No other ZIP5 codes exhibited similarly high response rates at meaningful volume.</p>
<p><strong>High-response ZIP5 segments (response_rate &gt; 0.20, n &gt; 40)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>zip5</th>
<th style="text-align: right;">response_rate (<code>res1_yes</code>)</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>00801</td>
<td style="text-align: right;">0.412470</td>
<td style="text-align: right;">1668</td>
</tr>
<tr class="even">
<td>00804</td>
<td style="text-align: right;">0.344086</td>
<td style="text-align: right;">186</td>
</tr>
</tbody>
</table>
<p>These two ZIP codes are treated as a distinct segment in modeling through an indicator feature.</p>
<hr>
</section>
</section>
<section id="modeling-approach" class="level2">
<h2 class="anchored" data-anchor-id="modeling-approach">Modeling Approach</h2>
<section id="baselines-logistic-regression-lr1lr2" class="level3">
<h3 class="anchored" data-anchor-id="baselines-logistic-regression-lr1lr2">Baselines: logistic regression (LR1–LR2)</h3>
<section id="feature-engineering-anomaly-indicator-isweird" class="level4">
<h4 class="anchored" data-anchor-id="feature-engineering-anomaly-indicator-isweird">Feature engineering: anomaly indicator (<code>isweird</code>)</h4>
<p>A binary feature, <code>isweird</code>, flags whether a customer is in the anomalous ZIP codes identified above:</p>
<ul>
<li><code>isweird = 1</code> if <code>zip5 ∈ {00801, 00804}</code>, otherwise <code>0</code>.</li>
</ul>
<p>This design isolates a localized geographic effect without relying solely on broader ZIP binning.</p>
</section>
<section id="baseline-comparison-impact-of-isweird" class="level4">
<h4 class="anchored" data-anchor-id="baseline-comparison-impact-of-isweird">Baseline comparison: impact of <code>isweird</code></h4>
<p>To quantify the incremental value of the anomaly indicator, two logistic regression models were evaluated on the validation sample:</p>
<ul>
<li><strong>LR1:</strong> baseline model using the original predictors<br>
</li>
<li><strong>LR2:</strong> LR1 plus <code>isweird</code></li>
</ul>
<p>Both models use the same preprocessing (categorical encoding for discrete fields).</p>
<section id="validation-confusion-matrices" class="level5">
<h5 class="anchored" data-anchor-id="validation-confusion-matrices">Validation confusion matrices</h5>
<p><strong>LR1 (baseline)</strong><br>
- TP = 749, FP = 6,188, TN = 15,209, FN = 354</p>
<p><strong>LR2 (+ isweird)</strong><br>
- TP = 743, FP = 5,736, TN = 15,661, FN = 360</p>
</section>
<section id="validation-profit-metrics" class="level5">
<h5 class="anchored" data-anchor-id="validation-profit-metrics">Validation profit metrics</h5>
<p><strong>Table 4. Profit comparison on validation sample</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th style="text-align: right;">Profit (validation)</th>
<th style="text-align: right;">Projected profit</th>
<th style="text-align: right;">ROME</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LR1</td>
<td style="text-align: right;">35,158.83</td>
<td style="text-align: right;">1,192,795.11</td>
<td style="text-align: right;">3.59</td>
</tr>
<tr class="even">
<td>LR2</td>
<td style="text-align: right;">35,444.61</td>
<td style="text-align: right;">1,202,490.81</td>
<td style="text-align: right;">3.88</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation.</strong> Adding <code>isweird</code> improves profit and ROME relative to the baseline. The gain is driven primarily by a reduction in false positives (FP decreases from 6,188 to 5,736), which improves mailing efficiency without materially changing the count of false negatives.</p>
</section>
</section>
<section id="lr1-baseline-logistic-regression" class="level4">
<h4 class="anchored" data-anchor-id="lr1-baseline-logistic-regression">LR1: baseline logistic regression</h4>
<p>Adding the anomaly indicator (<code>isweird</code>) improved both <strong>validation profit</strong> and <strong>ROME</strong> relative to the baseline logistic regression, indicating better campaign efficiency under the profit framework. To interpret what the baseline model is learning, Table X summarizes the key signals from the LR1 coefficient output.</p>
<section id="model-fit-lr1" class="level5">
<h5 class="anchored" data-anchor-id="model-fit-lr1">Model fit (LR1)</h5>
<ul>
<li><strong>AUC:</strong> 0.755<br>
</li>
<li><strong>McFadden pseudo R²:</strong> 0.114<br>
</li>
<li><strong>Overall model test:</strong> χ²(29) = 2289.8, p &lt; 0.001<br>
</li>
<li><strong>Sample size:</strong> 52,500 (training)</li>
</ul>
<p>These statistics indicate the model has meaningful discriminative power for ranking customers, although the pseudo R² suggests substantial unexplained variation remains—typical for response modeling with sparse outcomes.</p>
</section>
<section id="key-drivers-lr1" class="level5">
<h5 class="anchored" data-anchor-id="key-drivers-lr1">Key drivers (LR1)</h5>
<p>Odds ratios (OR) below are interpreted holding other variables constant:</p>
<ul>
<li><p><strong>Prior upgrade behavior (<code>upgraded=1</code>): OR = 2.616 (p &lt; 0.001)</strong><br>
Customers with prior upgrade history are much more likely to respond to the upgrade offer.</p></li>
<li><p><strong>Currently on version 1 (<code>version1=1</code>): OR = 2.113 (p &lt; 0.001)</strong><br>
Being on an older version is strongly associated with upgrade likelihood.</p></li>
<li><p><strong>Ordering frequency (<code>numords</code>): OR = 1.259 per additional order (p &lt; 0.001)</strong><br>
More prior orders correlate with higher probability of responding.</p></li>
<li><p><strong>Recency (<code>last</code>): OR = 0.957 per additional month since last order (p &lt; 0.001)</strong><br>
Longer time since last purchase reduces response likelihood, consistent with customer inactivity.</p></li>
<li><p><strong>Tax product ownership (<code>owntaxprod=1</code>): OR = 1.356 (p = 0.003)</strong><br>
Ownership of related products is associated with higher response propensity.</p></li>
<li><p><strong>Spend (<code>dollars</code>): OR ≈ 1.001 per dollar (p &lt; 0.001)</strong><br>
The per-dollar effect is small by construction; the practical impact depends on the spend range across customers.</p></li>
</ul>
</section>
<section id="limited-effects-lr1" class="level5">
<h5 class="anchored" data-anchor-id="limited-effects-lr1">Limited effects (LR1)</h5>
<ul>
<li><strong>Gender (<code>sex</code>)</strong> and <strong>business flag (<code>bizflag</code>)</strong> are not statistically significant in the baseline specification.</li>
<li><strong>Tenure since original purchase (<code>sincepurch</code>)</strong> is not significant once recency and purchase behavior are included.</li>
</ul>
</section>
</section>
<section id="geographic-effects-lr1" class="level4">
<h4 class="anchored" data-anchor-id="geographic-effects-lr1">Geographic effects (LR1)</h4>
<p><code>zip_bins</code> shows large differences relative to the reference bin, with most bins having substantially lower odds than the reference category. This aligns with the earlier EDA result that a localized geographic segment behaves differently and supports isolating that segment explicitly (rather than relying on binning alone).</p>
<p><strong>Figure 1. LR1 prediction profiles across key predictors</strong><br>
<img src="figures/fig1_lr1_prediction_profiles.png" id="fig-lr1-profiles" class="img-fluid" alt="Figure 1. LR1 prediction profiles across key predictors"></p>
<p>Response probability is dominated by geography: <code>zip_bins = 1</code> is a clear outlier, while other bins remain near a low baseline. Behavioral variables show predictable structure—probability increases with <code>numords</code> and is higher for <code>upgraded = 1</code> and <code>version1 = 1</code>. Recency is strongly negative: response probability declines as <code>last</code> increases. <code>sex</code>, <code>bizflag</code>, and <code>sincepurch</code> are nearly flat over the plotted ranges, suggesting limited incremental value in this specification.</p>
<p><strong>Figure 2. LR1 permutation importance (AUC decrease)</strong><br>
<img src="figures/fig2_lr1_permutation_importance.png" id="fig-lr1-permimp" class="img-fluid" alt="Figure 2. LR1 permutation importance (AUC decrease)"></p>
<p>Permutation importance ranks <code>zip_bins</code> as the strongest driver of model discrimination, followed by <code>upgraded</code> and <code>last</code>. <code>numords</code> and <code>version1</code> provide moderate contribution; remaining variables add minimal lift. The concentration of signal in the geography feature supports isolating the outlier ZIP behavior explicitly (via <code>isweird</code>) rather than relying on broad ZIP binning alone.</p>
</section>
<section id="lr2-enhanced-logistic-regression-anomalous-zip-isolation" class="level4">
<h4 class="anchored" data-anchor-id="lr2-enhanced-logistic-regression-anomalous-zip-isolation">LR2: enhanced logistic regression (anomalous ZIP isolation)</h4>
<p>LR2 extends the baseline model by adding <code>isweird</code>, a binary indicator for ZIP codes 00801 and 00804. This feature captures a localized geographic segment with unusually high wave-1 response.</p>
<section id="model-fit-lr2" class="level5">
<h5 class="anchored" data-anchor-id="model-fit-lr2">Model fit (LR2)</h5>
<ul>
<li><strong>AUC:</strong> 0.768 (vs 0.755 in LR1)<br>
</li>
<li><strong>McFadden pseudo R²:</strong> 0.148 (vs 0.114 in LR1)<br>
</li>
<li><strong>Overall model test:</strong> χ²(30) = 2965.6, p &lt; 0.001</li>
</ul>
<p>These changes indicate improved ranking performance after accounting for the anomalous ZIP segment.</p>
</section>
<section id="key-coefficients-lr2" class="level5">
<h5 class="anchored" data-anchor-id="key-coefficients-lr2">Key coefficients (LR2)</h5>
<p><code>isweird</code> is the dominant effect in the model:</p>
<ul>
<li><strong><code>isweird = 1</code>: OR = 24.6, p &lt; 0.001</strong><br>
Customers in ZIP codes 00801/00804 have substantially higher odds of responding, even after controlling for purchase behavior and product history.</li>
</ul>
<p>Core purchase-history signals remain stable and directionally consistent: - <strong><code>upgraded = 1</code>: OR = 2.74, p &lt; 0.001</strong> - <strong><code>version1 = 1</code>: OR = 2.18, p &lt; 0.001</strong> - <strong><code>numords</code>: OR = 1.28 per additional order, p &lt; 0.001</strong> - <strong><code>last</code>: OR = 0.956 per additional month since last order, p &lt; 0.001</strong> - <strong><code>owntaxprod = 1</code>: OR = 1.38, p = 0.002</strong></p>
<p>After introducing <code>isweird</code>, most <code>zip_bins</code> coefficients shrink toward neutrality and many become statistically insignificant, indicating that the earlier geographic pattern was primarily driven by the two outlier ZIP codes rather than broad differences across bins.</p>
</section>
<section id="variable-importance" class="level5">
<h5 class="anchored" data-anchor-id="variable-importance">Variable importance</h5>
<p>Figure confirms the same conclusion from a predictive standpoint. Permuting <code>isweird</code> produces the largest AUC degradation, followed by <code>upgraded</code> and <code>last</code>. <code>zip_bins</code> contributes relatively little once the outlier ZIP behavior is modeled explicitly.</p>
</section>
</section>
</section>
<section id="feature-refinement-version-path-construction" class="level3">
<h3 class="anchored" data-anchor-id="feature-refinement-version-path-construction">Feature refinement: version path construction</h3>
<p><strong>Figure 3. LR2 permutation importance (AUC decrease)</strong><br>
<img src="figures/fig3_lr2_permutation_importance.png" id="fig-lr2-permimp" class="img-fluid" alt="Figure 3. LR2 permutation importance (AUC decrease)"></p>
<p><code>isweird</code> is the dominant driver of LR2 discrimination: permuting it produces the largest AUC drop, far exceeding any other feature. After isolating the 00801/00804 segment, <code>zip_bins</code> contributes little incremental lift, while <code>upgraded</code> and purchase recency (<code>last</code>) remain the strongest broad-based predictors outside the anomaly. This supports modeling the outlier ZIP behavior explicitly with <code>isweird</code> rather than relying on ZIP-bin effects that would blur a concentrated segment signal.</p>
<p><strong>Figure 4. LR2 prediction profiles across key predictors</strong><br>
<img src="figures/fig4_lr2_prediction_profiles.png" id="fig-lr2-profiles" class="img-fluid" alt="Figure 4. LR2 prediction profiles across key predictors"></p>
<p>After adding <code>isweird</code>, the geographic spike shifts from <code>zip_bins</code> to the anomaly indicator. Predicted probability increases sharply when <code>isweird = 1</code>, while the <code>zip_bins</code> profile becomes largely flat, indicating limited incremental segmentation value once the outlier ZIPs are modeled explicitly. Purchase-history signals remain stable: probability increases with <code>numords</code>, and is higher for <code>upgraded = 1</code> and <code>version1 = 1</code>, while <code>last</code> remains strongly negative.</p>
<p>On the validation sample, LR2 (baseline predictors + <code>isweird</code>, with <code>zip_bins</code> retained) achieves <strong>profit = 35,444.61</strong> and <strong>ROME = 3.88</strong>, with projected profit of <strong>1,202,490.81</strong>. The confusion matrix is TP = 743, FP = 5,736, TN = 15,661, FN = 360. Relative to LR1, the primary change is a reduction in false positives (fewer low-probability customers mailed), which improves campaign efficiency while keeping overall capture of responders comparable.</p>
<section id="consolidating-version1-and-upgraded" class="level4">
<h4 class="anchored" data-anchor-id="consolidating-version1-and-upgraded">Consolidating <code>version1</code> and <code>upgraded</code></h4>
<p><strong>Figure 5. LR2 prediction profiles for key predictors</strong><br>
<img src="figures/fig5_lr2_prediction_profiles.png" id="fig-lr2-profiles" class="img-fluid" alt="Figure 5. LR2 prediction profiles for key predictors"></p>
<p>The prediction profiles show positive shifts for both <code>version1 = 1</code> and <code>upgraded = 1</code>, but these fields describe overlapping aspects of product history and are not mutually exclusive. To make version behavior interpretable and usable for targeting, the two indicators are recoded into a single categorical feature, <code>version_upgrade</code>, representing mutually exclusive version paths.</p>
<p><strong>Definition of <code>version_upgrade</code> (derived from <code>version1</code> and <code>upgraded</code>)</strong></p>
<ul>
<li><code>version1 = 1</code>, <code>upgraded = 0</code> → <strong>category 0</strong>: currently on version 1, no prior upgrade (n = 16,050)<br>
</li>
<li><code>version1 = 0</code>, <code>upgraded = 1</code> → <strong>category 1</strong>: upgraded to version 2 (n = 15,629)<br>
</li>
<li><code>version1 = 0</code>, <code>upgraded = 0</code> → <strong>category 2</strong>: directly purchased version 2 (n = 43,321)<br>
</li>
<li><code>version1 = 1</code>, <code>upgraded = 1</code> → not observed in the dataset</li>
</ul>
<p>This recode removes ambiguity in interpretation and prevents the model from splitting a single business concept across two correlated indicators.</p>
</section>
<section id="defining-version_upgrade" class="level4">
<h4 class="anchored" data-anchor-id="defining-version_upgrade">Defining <code>version_upgrade</code></h4>
<p><code>version1</code> and <code>upgraded</code> describe overlapping aspects of product history and are difficult to interpret separately. They are recoded into a single categorical feature, <code>version_upgrade</code>, representing mutually exclusive version paths:</p>
<ul>
<li><code>version1 = 1</code>, <code>upgraded = 0</code> → <strong><code>version_upgrade = 0</code></strong>: currently on version 1, no prior upgrade (n = 16,050)<br>
</li>
<li><code>version1 = 0</code>, <code>upgraded = 1</code> → <strong><code>version_upgrade = 1</code></strong>: upgraded to version 2 (n = 15,629)<br>
</li>
<li><code>version1 = 0</code>, <code>upgraded = 0</code> → <strong><code>version_upgrade = 2</code></strong>: directly purchased version 2 (n = 43,321)<br>
</li>
<li><code>version1 = 1</code>, <code>upgraded = 1</code> → not observed in the dataset</li>
</ul>
<p>This change is made for interpretability and reporting consistency. Model scoring is unchanged when <code>version1</code> and <code>upgraded</code> are replaced by <code>version_upgrade</code>.</p>
<p><strong>Figure 6. Predicted response by version path (<code>version_upgrade</code>)</strong><br>
<img src="figures/fig6_version_upgrade_pred.png" id="fig-version-upgrade" class="img-fluid" alt="Figure 6. Predicted response by version path (version_upgrade)"></p>
<p>Customers who previously <strong>upgraded to version 2</strong> have the highest predicted response. Customers still on <strong>version 1</strong> score next. Customers who <strong>directly purchased version 2</strong> have the lowest predicted response, indicating lower incremental upgrade propensity under the wave-1 offer.</p>
</section>
</section>
<section id="benchmark-mail-to-all-strategy" class="level3">
<h3 class="anchored" data-anchor-id="benchmark-mail-to-all-strategy">Benchmark: mail-to-all strategy</h3>
<p>A mail-to-all (“spam”) strategy was evaluated as a benchmark to ensure that targeting adds incremental value versus sending wave-2 to every eligible business.</p>
<p>On the validation sample, mailing to all customers yields the following confusion matrix:</p>
<ul>
<li>TP = 1,103<br>
</li>
<li>FP = 21,397<br>
</li>
<li>TN = 0<br>
</li>
<li>FN = 0</li>
</ul>
<p>Financial results for the mail-to-all benchmark are:</p>
<ul>
<li><strong>Profit (validation): 34,455.00</strong><br>
</li>
<li><strong>Projected profit: 1,168,918.80</strong><br>
</li>
<li><strong>ROME: 1.09</strong></li>
</ul>
<p>This benchmark underperforms the targeted logistic regression approaches (e.g., LR2), indicating that selective mailing improves profitability by avoiding low-probability customers. As a result, subsequent work focuses on models that improve ranking quality beyond logistic regression, including neural network classifiers and interaction specifications.</p>
</section>
<section id="neural-network-exploration" class="level3">
<h3 class="anchored" data-anchor-id="neural-network-exploration">Neural network exploration</h3>
<p>A simple multilayer perceptron (MLP) classifier with a single hidden unit was trained on the same inputs used in the logistic model (including <code>isweird</code> and <code>version_upgrade</code>). The objective of this step was to test whether a nonlinear learner identifies materially different structure or improves ranking beyond the logistic specification.</p>
<p><strong>Figure 7. MLP (1-unit) prediction profiles across key predictors</strong><br>
<img src="figures/fig7_mlp1unit_prediction_profiles.png" id="fig-mlp1unit-profiles" class="img-fluid" alt="Figure 7. MLP (1-unit) prediction profiles across key predictors"></p>
<p><strong>Figure 8. MLP (1-unit) permutation importance (AUC decrease)</strong><br>
<img src="figures/fig8_mlp1unit_permutation_importance.png" id="fig-mlp1unit-permimp" class="img-fluid" alt="Figure 8. MLP (1-unit) permutation importance (AUC decrease)"></p>
<p>The prediction profiles and permutation importance ranking mirror the logistic results. <code>isweird</code> remains the dominant signal, followed by purchase recency (<code>last</code>) and version path (<code>version_upgrade</code>), with <code>numords</code> providing moderate lift. Most <code>zip_bins</code> indicators contribute little once the anomaly ZIP behavior is isolated.</p>
<p>A one-unit MLP is a minimal nonlinear extension and, in practice, behaves similarly to a generalized linear model for this feature set. Because this configuration did not surface new segment structure or materially different drivers, it was treated as a baseline neural-network check rather than a candidate final model.</p>
<p><strong>Figure 9. MLP permutation importance with a larger hidden layer</strong><br>
<img src="figures/fig9_mlp_hidden10_permimp.png" id="fig-mlp-hidden10-permimp" class="img-fluid" alt="Figure 9. MLP permutation importance with a larger hidden layer"></p>
<p>Across both configurations, <code>isweird</code> remains the largest contributor to discrimination, confirming that the anomaly ZIP segment is the strongest signal in the data. Increasing model complexity shifts the relative importance among several features—most noticeably <code>version_upgrade</code>, <code>last</code>, <code>sincepurch</code>, and <code>sex</code>—indicating that nonlinear interactions may be present even when the top driver is unchanged. These shifts are treated as hypothesis-generating: they motivate testing explicit interaction terms in a constrained model (e.g., logistic regression with selected interactions) rather than relying on depth alone.</p>
<section id="mlp-check-single-hidden-unit" class="level4">
<h4 class="anchored" data-anchor-id="mlp-check-single-hidden-unit">MLP check: single hidden unit</h4>
<p>Under the larger MLP configuration, the relative importance of recency (<code>last</code>) increases and several effects appear to vary across segments rather than remaining parallel shifts. Interaction plots highlight three patterns that warrant explicit testing in a constrained model: (1) response differences by <code>zip_bins</code> vary by <code>sex</code>, (2) the uplift from <code>isweird</code> differs across version paths (<code>version_upgrade</code>), and (3) the uplift from <code>isweird</code> varies with ordering behavior (<code>numords</code>).</p>
<p>As a screening step, the MLP with a larger hidden layer was evaluated on the validation sample to confirm it remains a viable ranking model. Validation results are TP = 666, FP = 5,398, TN = 15,999, FN = 437 with <strong>projected profit = 1,065,600.97</strong> and <strong>ROME = 3.67</strong>. This underperforms LR2 on projected profit, so the MLP is used here primarily to motivate interaction candidates rather than as the final scoring model.</p>
</section>
</section>
<section id="lr3-logistic-regression-with-interactions" class="level3">
<h3 class="anchored" data-anchor-id="lr3-logistic-regression-with-interactions">LR3: logistic regression with interactions</h3>
<p>Deeper MLP configurations did not deliver a profit lift over the tuned logistic baseline, so interaction effects were tested directly within logistic regression. LR3 extends LR2 by adding three interaction specifications: <code>sex × zip_bins</code>, <code>isweird × version_upgrade</code>, and <code>isweird × numords</code>.</p>
<p>On the validation sample, LR3 improves results versus LR2: - <strong>Profit (validation): 35,940.90</strong><br>
- <strong>Projected profit: 1,219,324.02</strong><br>
- <strong>ROME: 3.92</strong></p>
<section id="what-changed-in-lr3" class="level4">
<h4 class="anchored" data-anchor-id="what-changed-in-lr3">What changed in LR3</h4>
<ul>
<li>The anomaly ZIP segment remains the dominant effect: <strong><code>isweird</code> OR = 22.22 (p &lt; 0.001)</strong>.</li>
<li>Version path separation remains strong: <strong><code>version_upgrade[1]</code> OR = 1.27 (p &lt; 0.001)</strong> and <strong><code>version_upgrade[2]</code> OR = 0.42 (p &lt; 0.001)</strong> relative to the reference category.</li>
<li>Among the interaction terms, the clearest incremental effect is <strong><code>isweird × version_upgrade[2]</code> OR = 1.62 (p = 0.002)</strong>, indicating that within the anomaly ZIP segment, customers who directly purchased version 2 exhibit higher incremental upgrade propensity than the baseline version path.</li>
<li><strong><code>isweird × numords</code> is not supported (p = 0.296)</strong>, suggesting that the anomaly ZIP uplift is largely additive with respect to ordering frequency.</li>
</ul>
<p>Several <code>sex × zip_bins</code> coefficients are statistically significant, implying that geographic differences are not uniform across gender categories in some bins. Because this interaction family introduces many parameters, its value is assessed primarily by validation profit rather than by individual coefficient significance.</p>
</section>
<section id="model-specification-and-validation-performance" class="level4">
<h4 class="anchored" data-anchor-id="model-specification-and-validation-performance">Model specification and validation performance</h4>
<p>MLP1 is selected as the final scoring model because it delivers the highest projected profit on the validation sample among the evaluated approaches. Hyperparameters were chosen through cross-validated search over network depth, regularization, and learning rate. Recall was used during tuning to avoid missing responders, and the final selection criterion was validation profit.</p>
<p>The selected configuration uses a three-layer architecture <code>(3, 3, 3)</code> with L2 regularization <code>alpha = 0.0095</code> (solver: Adam). Validation performance:</p>
<ul>
<li>Confusion matrix: TP = 768, FP = 6,292, TN = 15,105, FN = 335<br>
</li>
<li><strong>Profit (validation): 36,125.40</strong><br>
</li>
<li><strong>Projected profit: 1,225,587.45</strong><br>
</li>
<li><strong>ROME: 3.63</strong></li>
</ul>
</section>
<section id="interpretation-permutation-importance-mlp1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-permutation-importance-mlp1">Interpretation: permutation importance (MLP1)</h4>
<p><strong>Figure 10. MLP1 permutation importance (AUC decrease)</strong><br>
<img src="figures/fig10_mlp1_permutation_importance.png" id="fig-mlp1-permimp" class="img-fluid" alt="Figure 10. MLP1 permutation importance (AUC decrease)"></p>
<p>The importance ranking is concentrated in a small set of features. <code>isweird</code> produces the largest AUC drop when permuted, indicating that the anomaly ZIP segment is the strongest discriminator.</p>
<hr>
</section>
</section>
</section>
<section id="recommendation-and-expected-impact" class="level2">
<h2 class="anchored" data-anchor-id="recommendation-and-expected-impact">Recommendation and Expected Impact</h2>
<section id="recommended-wave-2-targeting-rule" class="level3">
<h3 class="anchored" data-anchor-id="recommended-wave-2-targeting-rule">Recommended wave-2 targeting rule</h3>
<p>Use the final scoring model (MLP1) to rank all wave-1 non-responders by predicted response probability. To account for lower expected responsiveness in wave-2, scale predicted probabilities by <strong>50% of the wave-1 rate</strong>. Mail to customers whose adjusted probability exceeds the campaign break-even response rate:</p>
<ul>
<li><strong>Mail if:</strong> <code>0.5 × p̂(response) ≥ 0.0235</code></li>
</ul>
<p>This rule targets customers expected to generate positive incremental profit after mailing costs.</p>
</section>
<section id="expected-financial-impact" class="level3">
<h3 class="anchored" data-anchor-id="expected-financial-impact">Expected financial impact</h3>
<p>Applying the recommended targeting policy yields an expected <strong>projected profit of 1,225,587.45</strong> from the wave-2 mailing under the stated wave-2 response adjustment and campaign economics. This materially outperforms a mail-to-all strategy and the logistic regression baselines evaluated during model selection.</p>
</section>
<section id="operational-notes" class="level3">
<h3 class="anchored" data-anchor-id="operational-notes">Operational notes</h3>
<ul>
<li>The model should be used for <strong>ranking and cutoff selection</strong> rather than as a literal probability forecast.</li>
<li>Performance should be monitored after wave-2 results arrive, with particular attention to the stability of the anomaly ZIP segment captured by <code>isweird</code>.</li>
</ul>
<hr>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Wave-1 response behavior is concentrated in a small set of signals: a localized geographic segment (ZIPs 00801 and 00804) and purchase-history indicators such as version path, recency, and ordering frequency. These patterns were consistent across models and remained the primary drivers of response separation.</p>
<p>The selected modeling approach provides a practical scoring framework that can be reused for future waves. After wave-2, results should be reviewed to confirm that the anomaly ZIP segment and version-path effects remain stable, and the targeting cutoff should be recalibrated using observed wave-2 economics and response rates.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>